package GUI;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.sun.org.apache.xpath.internal.functions.FuncFalse;
import modelos.ListaMoviles;
import modelos.Movil;
import Webs.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;

public class App {

    private JPanel panelMain;
    private JComboBox Marca;
    private JTextField Modelo;
    private JRadioButton btn_Amazon;
    private JRadioButton btn_PCComp;
    private JRadioButton btn_Fnac;
    private JButton btn_Buscar;
    private JList list1;
    private JList list2;
    private JList list3;


    public App() {
        btn_Buscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                //llamar la clase controladora
                if (btn_Amazon.isSelected()) {
                    ListaMoviles listaAmazon;
                    Amazon a = new Amazon();
                    listaAmazon = new ListaMoviles(a.Chrome(Marca.getSelectedItem().toString(), Modelo.getText()));
                    list1.setModel(listaAmazon);

                }

                if (btn_Fnac.isSelected()) {
                    ListaMoviles listaFnac;
                    Fnac f = new Fnac();
                    listaFnac = new ListaMoviles(f.Chrome(Marca.getSelectedItem().toString(), Modelo.getText()));
                    list2.setModel(listaFnac);

                }

                if (btn_PCComp.isSelected()) {
                    ListaMoviles listaPCComp;
                    PCComponet p = new PCComponet();
                    listaPCComp = new ListaMoviles(p.Chrome(Marca.getSelectedItem().toString(), Modelo.getText()));
                    list3.setModel(listaPCComp);


                }

                //HACER UNA TABLA O ALGO ASÍ CON listaAmazon, listaFnac y listaPCComp


            }
        });

        btn_Buscar.setEnabled(false);


        Modelo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                super.keyTyped(e);
                if ((Modelo.getText().length() > 0) &&
                        (btn_Amazon.isSelected() || btn_PCComp.isSelected() || btn_Fnac.isSelected())) {
                    btn_Buscar.setEnabled(true);

                } else {
                    btn_Buscar.setEnabled(false);
                }

            }
        });


        btn_Amazon.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if ((Modelo.getText().length() > 0) &&
                        (btn_Amazon.isSelected() || btn_PCComp.isSelected() || btn_Fnac.isSelected())) {
                    btn_Buscar.setEnabled(true);

                } else {
                    btn_Buscar.setEnabled(false);
                }
            }
        });
        btn_PCComp.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if ((Modelo.getText().length() > 0) &&
                        (btn_Amazon.isSelected() || btn_PCComp.isSelected() || btn_Fnac.isSelected())) {
                    btn_Buscar.setEnabled(true);

                } else {
                    btn_Buscar.setEnabled(false);
                }
            }
        });
        btn_Fnac.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if ((Modelo.getText().length() > 0) &&
                        (btn_Amazon.isSelected() || btn_PCComp.isSelected() || btn_Fnac.isSelected())) {
                    btn_Buscar.setEnabled(true);

                } else {
                    btn_Buscar.setEnabled(false);
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Búsqueda de Móviles");
        frame.setContentPane(new App().panelMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);


    }


    private void createUIComponents(List<Movil> listaAmazon, List<Movil> listaFnac, List<Movil> listaPcComponents) {
        // TODO: place custom component creation code here
        btn_Buscar.setEnabled(false);
    }

    {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(8, 5, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.setAlignmentX(1.0f);
        panelMain.setAlignmentY(1.0f);
        panelMain.setBackground(new Color(-2699061));
        panelMain.setMinimumSize(new Dimension(408, 499));
        panelMain.setPreferredSize(new Dimension(308, 399));
        Marca = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Samsung");
        defaultComboBoxModel1.addElement("LG");
        defaultComboBoxModel1.addElement("Sony");
        defaultComboBoxModel1.addElement("HUAWEI");
        defaultComboBoxModel1.addElement("Motorola");
        defaultComboBoxModel1.addElement("Apple");
        defaultComboBoxModel1.addElement("ONEPLUS");
        defaultComboBoxModel1.addElement("Lenovo");
        defaultComboBoxModel1.addElement("Xiaomi");
        Marca.setModel(defaultComboBoxModel1);
        panelMain.add(Marca, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Modelo = new JTextField();
        Modelo.setText("");
        panelMain.add(Modelo, new GridConstraints(1, 1, 2, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btn_Amazon = new JRadioButton();
        btn_Amazon.setText("Amazon");
        panelMain.add(btn_Amazon, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btn_PCComp = new JRadioButton();
        btn_PCComp.setText("PC Componentes");
        panelMain.add(btn_PCComp, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btn_Fnac = new JRadioButton();
        btn_Fnac.setText("Fnac");
        panelMain.add(btn_Fnac, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btn_Buscar = new JButton();
        btn_Buscar.setText("Buscar");
        panelMain.add(btn_Buscar, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-16777216));
        label1.setText("Marca:");
        panelMain.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-16777216));
        label2.setText("Modelo:");
        panelMain.add(label2, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelMain.add(spacer1, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panelMain.add(spacer2, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelMain.add(scrollPane1, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        list1 = new JList();
        scrollPane1.setViewportView(list1);
        final JScrollPane scrollPane2 = new JScrollPane();
        panelMain.add(scrollPane2, new GridConstraints(7, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        list2 = new JList();
        scrollPane2.setViewportView(list2);
        final JScrollPane scrollPane3 = new JScrollPane();
        panelMain.add(scrollPane3, new GridConstraints(7, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        list3 = new JList();
        scrollPane3.setViewportView(list3);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
